# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import usb_arm


def main():
    """
    PoC robot arm test program
    Assumes arm is in central position and grips are open.
    If the arm is not in this position then damage to the gears and / or motors may occur
    """
    actions = [
        [usb_arm.GripsClose],           # Motor 1
        [usb_arm.GripsOpen],            # Motor 1
        [usb_arm.WristDown, 2],         # Motor 2
        [usb_arm.WristUp, 2],           # Motor 2
        [usb_arm.ElbowDown, 2],         # Motor 3
        [usb_arm.ElbowUp, 2],           # Motor 3
        [usb_arm.ShoulderDown, 2],      # Motor 4
        [usb_arm.ShoulderUp, 2],        # Motor 4
        [usb_arm.BaseClockWise, 2],     # Motor 5
        [usb_arm.BaseCtrClockWise, 2],  # Motor 5
    ]

    arm = usb_arm.Arm()
    arm.doActions(usb_arm.blink)
    arm.doActions(actions)
    arm.doActions(usb_arm.blink)


# Ensure that main() is called when this file is executed from the commandline
if __name__ == "__main__":
    main()
